services:
  - type: web
    name: et-backend
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
    startCommand: python start_server.py
    plan: free
    healthCheckPath: /health
    envVars:
      - key: DEBUG
        value: false
      - key: HOST
        value: 0.0.0.0
      - key: WORKERS
        value: 1
      - key: LOG_LEVEL
        value: INFO
      - key: OCR_GPU_ENABLED
        value: false
      - key: PII_DETECTION_ENABLED
        value: true
      - key: LLM_VALIDATION_ENABLED
        value: true
